server:
  port: 8020
  
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/orders
    username: root
    password: root 
  ## Hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eventuatelocal.kafka.bootstrap.servers: localhost:9092

logging:
  level:
    org.hibernate.type: trace
    com.rara.toy1.order: debug        